paso por valor titulo a componente open dialog
acsantosabino/angular-med-store pull request #23
Opened 2019-01-17 19:47 UTC by netfanely

pequenha modificacion del componente open dialog, "paso por valor" angular cli 7 en documentos ts, html

2019-01-18 12:34 UTC, acsantosabino requested changes

2019-01-18 12:34 UTC, acsantosabino commented on angular-med-store/src/app/view-viewmodel/dialog-data/dialog-data.component.ts
>  export interface DialogData {
Essa interface não é necessária pois já temos a classe Produto. É melhor importar ela e usar seus atributos

2019-01-22 18:40 UTC, netfanely commented on angular-med-store/src/app/view-viewmodel/dialog-data/dialog-data.component.ts
>  export interface DialogData {
si me dices como, con gusto lo realizo ¬¬

2019-01-23 13:04 UTC, acsantosabino approved these changes

2019-01-23 13:05 UTC, merged