Estilização do header e do carrossel de produtos
acsantosabino/angular-med-store pull request #24
Opened 2019-01-18 04:29 UTC by danilloguimaraes

Estilização do header e do carrossel de produtos

2019-01-18 12:34 UTC, acsantosabino requested changes

2019-01-18 12:34 UTC, acsantosabino commented on angular-med-store/src/app/app.component.scss
> +    background-color: #00abdf;
importa no tema definido no style.scss pq assim a gente padroniza os componentes

2019-01-19 20:36 UTC, danilloguimaraes commented
Arthur as modificações solicitadas foram implementadas

2019-01-20 14:26 UTC, acsantosabino approved these changes
Aprovei com comentário. Da uma conferida

2019-01-20 14:26 UTC, acsantosabino commented on angular-med-store/src/app/app.component.html
> +    <div id="carrinho">
Precisa de um div dentro dou outro assim aqui?

2019-01-20 18:26 UTC, danilloguimaraes commented on angular-med-store/src/app/app.component.html
> +    <div id="carrinho">
Sim

2019-01-20 18:32 UTC, merged